### ISSUE TITLE
如果有国内的镜像网站就好了！

### ISSUE THREAD

**Issue by CnData07** [LiteLDev/docs#10]
目前lles开发的时候很难使用浏览器访问docs直接访问到文档，开了加速器进的很慢，些许时候会出现等半天也进不去的情况。迫切想要一个镜像网站了。
- Cent Chrome 版本 4.3.9.248（正式版本） （32 位） (Portable) (Chromium 86.0.4240.198)
- 移动网络
- Watt Toolkit（原Steam++）

**Comment by KawaiiNahida** [comment]
由于国内各种备案/收费/防御等等一系列问题，近期不会优先处理这个问题

**Comment by futrime** [comment]
Thank you for your report. We've just applied Cloudflare CDN to our website and your experience might be optimized. Have a try.
