### ISSUE TITLE
文档协议问题

### ISSUE THREAD

**Issue by Yushu2606** [LiteLDev/docs#17]
像文档这类不算“源代码”的应该用`CC-BY-SA`这类协议更合适吧？
参考：https://creativecommons.org/licenses/

**Comment by futrime** [comment]
Thank you for your question. We've already taken this into consideration before, only to find that keeping a license consistent with the main repository is the best solution, which is recommended by GitHub. If interested, please refer to https://choosealicense.com/non-software/
