### ISSUE TITLE
文档挂了

### ISSUE THREAD

**Issue by Sbaoor-fly** [LiteLDev/docs#2]
https://docs.litebds.com/zh-Hans/#/LLSEPluginDevelopment/

侧边栏失效了，切换不了页面

**Comment by Futrime** [comment]
@Sbaoor-fly 他这个bug是插件js还没下载完导致的

**Comment by futrime** [comment]
![image](https://user-images.githubusercontent.com/35801754/188034113-9c598e56-14a3-463d-9064-3e90d2b76036.png)

我测试了似乎没问题，怀疑是Docsify及其插件自身bug.
