### ISSUE TITLE
There should be more information in the documentation

### ISSUE THREAD

**Issue by harry-xi** [LiteLDev/docs#54]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/79187160/210934843-cb69df89-b0b6-4d0c-bf64-05fca73769c0.png)
These objects in the image exist in the scripting engine, and they are also important for scripting plugins in certain situations, but they are not mentioned in the documentation.

**Describe the solution you'd like**
Add some introduction to these objects

**Describe alternatives you've considered**
I am considering adding them to https://github.com/LiteLScript-Dev/HelperLib

**Comment by futrime** [comment]
@harry-xi Please help us complete them and open a PR

**Comment by harry-xi** [comment]
> @harry-xi Please help us complete them and open a PR

In fact, the main problem is that I don't know how to make this clear in the document.
