### ISSUE TITLE
中文搜索问题 pl.setGameMode 描述错误

### ISSUE THREAD

**Issue by engsr6982** [LiteLDev/docs#61]
**Describe the bug**
中文文档   脚本插件开发-玩家对象的pl. SetGameMode   mode: Integer参数中文描述错误
2应该为冒险模式 错误的描述成极限模式而英文文档没有这个描述错误

中文文档，搜索功能搜索不到pl.SetGameMode 这类新加的接口 而英文文档可以（尝试过清除缓存

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [iPhone11]
 - OS: [iOS15.7.1]
 - Browser [edge, safari]

**Additional context**

**Comment by ShrBox** [comment]
![image](https://user-images.githubusercontent.com/53301243/211762692-2c84d70b-c88e-44c7-b4ca-0181d5cdfd41.png)
？
